package br.com.suportempt.tela;

public class TelaUsuario extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_titulo = new javax.swing.JLabel();
        lb_observacao = new javax.swing.JLabel();
        lb_chamado = new javax.swing.JLabel();
        lb_observacao1 = new javax.swing.JLabel();
        icone_cad_chamado = new javax.swing.JLabel();
        icone_pesq_chamado = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuCadastrar = new javax.swing.JMenu();
        item_cad_chamado = new javax.swing.JMenuItem();
        menuPesquisar = new javax.swing.JMenu();
        item_pesq_chamado = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Suporte MPT");
        setPreferredSize(new java.awt.Dimension(595, 393));
        setResizable(false);

        lb_titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lb_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_titulo.setText("Bem Vindo ao Suporte MPT");

        lb_observacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_observacao.setText("E-mail da instituição e código do Patrimônio obrigátorios para registrar uma ocorrência.");

        lb_chamado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_chamado.setText("Clique no botão abaixo para criar um chamado, ou verificar se já há chamado aberto.");

        lb_observacao1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_observacao1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_observacao1.setText("Importante:");

        icone_cad_chamado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icone_cad_chamado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/cad_chamado.png"))); // NOI18N
        icone_cad_chamado.setToolTipText("Cadastrar Chamado");
        icone_cad_chamado.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Criar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP));
        icone_cad_chamado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icone_cad_chamado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icone_cad_chamadoMouseClicked(evt);
            }
        });

        icone_pesq_chamado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icone_pesq_chamado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/pesq_chamado.png"))); // NOI18N
        icone_pesq_chamado.setToolTipText("Verificar Chamado");
        icone_pesq_chamado.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Verificar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP));
        icone_pesq_chamado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icone_pesq_chamado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icone_pesq_chamadoMouseClicked(evt);
            }
        });

        menuCadastrar.setText("Cadastro");

        item_cad_chamado.setText("Chamado");
        item_cad_chamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_cad_chamadoActionPerformed(evt);
            }
        });
        menuCadastrar.add(item_cad_chamado);

        menuBar.add(menuCadastrar);

        menuPesquisar.setText("Pesquisa");

        item_pesq_chamado.setText("Verificar chamado");
        item_pesq_chamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_pesq_chamadoActionPerformed(evt);
            }
        });
        menuPesquisar.add(item_pesq_chamado);

        menuBar.add(menuPesquisar);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_observacao1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_observacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(lb_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_chamado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addComponent(icone_cad_chamado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(icone_pesq_chamado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lb_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_chamado, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(icone_cad_chamado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(icone_pesq_chamado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_observacao, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_observacao1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void item_pesq_chamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_pesq_chamadoActionPerformed
        new VerificarChamado().setVisible(true);
    }//GEN-LAST:event_item_pesq_chamadoActionPerformed

    private void item_cad_chamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_cad_chamadoActionPerformed
        new CadastrarChamado().setVisible(true);
    }//GEN-LAST:event_item_cad_chamadoActionPerformed

    private void icone_cad_chamadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icone_cad_chamadoMouseClicked
        new CadastrarChamado().setVisible(true);
    }//GEN-LAST:event_icone_cad_chamadoMouseClicked

    private void icone_pesq_chamadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icone_pesq_chamadoMouseClicked
        new VerificarChamado().setVisible(true);
    }//GEN-LAST:event_icone_pesq_chamadoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icone_cad_chamado;
    private javax.swing.JLabel icone_pesq_chamado;
    private javax.swing.JMenuItem item_cad_chamado;
    private javax.swing.JMenuItem item_pesq_chamado;
    private javax.swing.JLabel lb_chamado;
    private javax.swing.JLabel lb_observacao;
    private javax.swing.JLabel lb_observacao1;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenu menuPesquisar;
    // End of variables declaration//GEN-END:variables
}
